### ISSUE TITLE
1 урок. исправления

### ISSUE THREAD

**Issue by emptyb** [desardos/desardos.github.io#1]
Необходимо создать папку css c файлом css и оформлять внешний вид страницы там. 
body - зачем выравнивать его по- центру?
 Одинаковый id можно использовать всего лишь раз. Для удобства используют class=" ". чтобы можно было использовать определенный цсс в разных блоках. Исправьте везде с id на class.
# list- высоту нужно убрать.  margin можно прописать в 1 строку - margin:0 auto; не верное позиционирование. вместо position-relative; top:7px можно просто указать margin-top.

ФИО и Фото не по центру. Фото оборачиваем тегом div. 
Оборачиваем текстовые блоки в div. В div указываем левый падинг. margin-left убираем.

**Comment by emptyb** [comment]
остались ошибки после первого комента. не по центру фио и qa engineer. так же тут не надо оборачивать list2 в list. лучше разбить все дивы к примеру по подчеркиваниям.
необходимо избавиться от style в html. прописываем все в css. отступы разные между текстовыми элементами. сделайте визуально все более аккуратней. 
li точки вышли влево.
все должно быть в одну вертикальную линию кроме пунктов li

**Comment by NikitaMikhanchuk** [comment]
Простите, что означает « так же тут не надо оборачивать list2 в list. лучше
разбить все дивы к примеру по подчеркиваниям» ?

**Comment by emptyb** [comment]
.list лучше задать больше отступы. чтобы нижние подчеркивания не были так близко к краю тэга с классом list
.personInfo внутри него не надо оборачивать каждый пункт в свой div. лучше просто оставить структуру div class="personInfo" и внутри h1 img и p.
На одной странице может быть только один тег h1.
additionalInformation- не правильно задан класс. между словами необходимо задать разделитель "-". 
changePadding - можно удалить, он не нужет в данном случае. инфу оставив в диве additionalInformation
Очень много дивов. можно всю инфу разместить в 4-х. 1й- фио фото и текст. 2й блок- хочу изучать фронт енд с li. 3й блок- контактный телефон и вк 4й блок- мой фидбек

**Comment by emptyb** [comment]
list- margin:0 auto для гориз. выравнивания
additional_Information неверно подключен шрифт.
person_Info- на странице должен быть только один тег h1 уже писал в коментрии выше!
содержимое explain_Question_1 засунуть в additional_Information. 
так же с explain_Question_2 и отдельным тегом 'p' 
.delete_Indent прописал line-height:1px; убери это

**Comment by emptyb** [comment]
На одной странице может быть только один тег h1.
текст в теге h1 и так жирный. не нужно его оборачивать в strong.
структура в целом не корректна. надо засунуть в блок additional_Information блок ul, а в следующий additional_Information 3 тега Р с телефоном профилем вк и самой ссылкой, которую не нужно оборачивать в тег Р
